package com.charlieknudsen.myweather.transfer

class CurrentObservation {
    Image image
    DisplayLocation displayLocation
    ObservationLocation observationLocation
    String stationId             // "KMNSAINT13",
    String observationTime      // "Last Updated on August 2, 10:09 PM CDT",
    String observationTimeRfc822 // "Sat, 02 Aug 2014 22:09:03 -0500",
    String observationEpoch      // "1407035343",
    String localTimeRfc822     // "Sat, 02 Aug 2014 22:11:01 -0500",
    String localEpoch           // "1407035461",
    String localTzShort        // "CDT",
    String localTzLong         // "America/Chicago",
    String localTzOffset       // "-0500",
    String weather               // "Mostly Cloudy",
    String temperatureString     // "69.6 F (20.9 C)",
    Float tempF                  // 69.6,
    Float tempC                  // 20.9,
//    String "relative_humidity": "74%",
//    String "wind_string": "Calm",
//    String "wind_dir": "North",
//    String "wind_degrees": -999,
//    String "wind_mph": 0.0,
//    String "wind_gust_mph": 0,
//    String "wind_kph": 0,
//    String "wind_gust_kph": 0,
//    String "pressure_mb": "1018",
//    String "pressure_in": "30.08",
//    String "pressure_trend": "0",
//    String "dewpoint_string": "61 F (16 C)",
//    String "dewpoint_f": 61,
//    String "dewpoint_c": 16,
//    String "heat_index_string": "NA",
//    String "heat_index_f": "NA",
//    String "heat_index_c": "NA",
//    String "windchill_string": "NA",
//    String "windchill_f": "NA",
//    String "windchill_c": "NA",
//    String "feelslike_string": "69.6 F (20.9 C)",
//    String "feelslike_f": "69.6",
//    String "feelslike_c": "20.9",
//    String "visibility_mi": "9.0",
//    String "visibility_km": "14.5",
//    String "solarradiation": "--",
//    String "UV": "0", "precip_1hr_string": "-999.00 in ( 0 mm)",
//    String "precip_1hr_in": "-999.00",
//    String "precip_1hr_metric": " 0",
//    String "precip_today_string": "-999.00 in (-25375 mm)",
//    String "precip_today_in": "-999.00",
//    String "precip_today_metric": "--",
    String icon           // "mostlycloudy",
    String iconUrl       // "http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif",
    String forecastUrl   // "http://www.wunderground.com/US/MN/Saint_Paul.html",
    String historyUrl    // "http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KMNSAINT13",
    String obUrl         // "http://www.wunderground.com/cgi-bin/findweather/getForecast?query=44.914963,-93.166504",
//    String "nowcast": ""
}
